apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: be-app-container
        image: socketio-poc-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 8878
