apiVersion: v1
kind: Service
metadata:
  name: be-svc-external
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
