apiVersion: v1
kind: Service
metadata:
  name: be-svc-internal
spec:
  selector:
    app: backend
  ports:
    - name: socketio
      protocol: TCP
      port: 8878
      targetPort: 8878
  type: ClusterIP
