apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: be-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - name: socketio
      protocol: TCP
      port: 8878
      targetPort: 8878
  type: NodePort
