apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream frontend_app_http {
            server fe-svc:3000;
        }
        upstream backend_app_http {
            server be-svc-external:8080;
        }
        upstream backend_app_socketio {
            server be-svc-internal:8878;
        }
    
        server {
            listen 80;
    
            location / {
                proxy_pass http://frontend_app_http;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
        server {
            listen 8090;
    
            location / {
                proxy_pass http://backend_app_http;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
        server {
            listen 8091;
    
            location / {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $host;
    
              proxy_pass http://backend_app_socketio;
    
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
            }
        }
    }
