apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: gateway
  ports:
    - name: load
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30002
    - name: socketio
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30003
  type: NodePort
