services:
  nginx:
    image: nginx:latest
    ports:
      - "8090:80" # Map host port 8090 to container port 80
      - "8091:8091" # Map host port 8091 to container port 8091
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount our custom nginx.conf
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: be/.
    expose:
      - "8878"
    ports:
      - "30001:8080" # Map host port 30001 to container port 8080
    networks:
      - app_network

  frontend:
    build: fe/.
    ports:
      - "30000:3000" # Map host port 30000 to container port 3000

networks:
  app_network:
    driver: bridge
