services:
  gateway:
    image: nginx:latest
    ports:
      - "30000:80" # allow initial browser load thru gateway (host: 30000 -> container: 80)
      - "30002:8090" # allow browser to fetch http data thru gateway (host: 30002 -> container: 8080)
      - "30003:8091" # allow browser to fetch socketio data thru gateway (host: 30003 -> container: 8091)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount our custom nginx.conf
    depends_on:
      - backend

  backend:
    build: be/.
    expose:
      - "8878"
    ports:
      - "30001:8080" # backdoor for triggering socketio update via curl (host: 30001 -> container: 8080)

  frontend:
    build: fe/.
    expose:
      - "3000"
