apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: fe-app-container
        image: socketio-poc-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
